spring:
  application:
    name: fintrack-monolith
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: PRACTICESCHEMA
    password: PRACTICESCHEMA
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    #database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
server:
  port: 9123